# === Serveur ===
server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:hellmetz-keystore.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=hellmetz

# === Base de donnees (remplace ConnectionFactory.java) ===
spring.datasource.url=jdbc:postgresql://127.0.0.1:5433/hellmetz_db
spring.datasource.username=hellmetz
spring.datasource.password=VOLABEBOL_SERV_2261

# === Hibernate / JPA ===
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#a ete rajouter
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=hellmetz


# === Thymeleaf ===
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8





#a ete rajouter
# === HikariCP (pool de connexion) ===
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1800000


