# === Serveur ===
server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:hellmetz-keystore.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=hellmetz

# === Base de donnees (remplace ConnectionFactory.java) ===
spring.datasource.url=jdbc:postgresql://127.0.0.1:5433/hellmetz_db
spring.datasource.username=hellmetz
spring.datasource.password=VOLABEBOL_SERV_2261

# === Hibernate / JPA ===
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# === Thymeleaf ===
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
