# Param�tres de connexion PostgreSQL - HellMetz Festival

# URL de connexion � la base de donn�es localhost peut �tre
# remplac� par une adresse IP ou le nom du serveur
#db.url=jdbc:postgresql://192.168.1.200:5432/hellmetz_db
db.url=jdbc:postgresql://127.0.0.1:5433/hellmetz_db

# Nom d'utilisateur de la base de donn�es
db.user=hellmetz

# Mot de passe de la base de donn�es
db.password=VOLABEBOL_SERV_2261

# Pilote ou driver utilis� pour se connecter � la base de donn�es
# Peut �tre modifier en fonction du moteur de base de donn�es utilis�
db.driver=org.postgresql.Driver
